env:
  browser: true
  es6: true
extends:
  - "plugin:react/recommended"
  - airbnb
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  import/no-mutable-exports: 0
  no-underscore-dangle:
    - error
    - allow :
      - __REDUX_DEVTOOLS_EXTENSION__
settings:
  import/resolver: node
