plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"
yarnPath: .yarn/releases/yarn-berry.js
packageExtensions:
  "@ant-design/icons@*":
    peerDependencies:
      react-dom: ^16.0.0
  antd@*:
    peerDependencies:
      dayjs: ^1.8.18
  rc-animate@*:
    peerDependencies:
      react: ^16.0.0
      react-dom: ^16.0.0
  rc-collapse@*:
    peerDependencies:
      react: ^16.0.0
      react-dom: ^16.0.0
  rc-dialog@*:
    peerDependencies:
      react: ^16.0.0
      react-dom: ^16.0.0
  rc-drawer@*:
    peerDependencies:
      react-dom: ^16.0.0
  rc-field-form@*:
    peerDependencies:
      react-dom: ^16.0.0
  rc-input-number@*:
    peerDependencies:
      react: ^16.0.0
      react-dom: ^16.0.0
  rc-mentions@*:
    peerDependencies:
      react-dom: ^16.0.0
  rc-rate@*:
    peerDependencies:
      react: ^16.0.0
      react-dom: ^16.0.0
  rc-slider@*:
    peerDependencies:
      react: ^16.0.0
      react-dom: ^16.0.0
  rc-tabs@*:
    peerDependencies:
      react: ^16.0.0
  react-color@*:
    peerDependencies:
      react: ^16.0.0
